"""empty message

Revision ID: 46d833760e47
Revises: 234ffb71350e
Create Date: 2024-08-29 14:21:49.576438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d833760e47'
down_revision = '234ffb71350e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.Text(), nullable=True))

    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profile', schema=None) as batch_op:
        batch_op.drop_column('section')

    with op.batch_alter_table('patient_details', schema=None) as batch_op:
        batch_op.drop_column('section')

    # ### end Alembic commands ###
