"""empty message

Revision ID: 49e13e0ebbe6
Revises: 5700d4df99ea
Create Date: 2024-08-31 15:15:13.232837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e13e0ebbe6'
down_revision = '5700d4df99ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('used_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine_inventory')
    # ### end Alembic commands ###
