"""empty message

Revision ID: c760ec2c01e3
Revises: 49e13e0ebbe6
Create Date: 2024-08-31 16:07:36.772047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c760ec2c01e3'
down_revision = '49e13e0ebbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_column('qty')

    # ### end Alembic commands ###
