"""empty message

Revision ID: edefacb5d9f7
Revises: d781b76784e6
Create Date: 2024-08-30 14:03:39.829306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edefacb5d9f7'
down_revision = 'd781b76784e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floordb', schema=None) as batch_op:
        batch_op.alter_column('floor_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floordb', schema=None) as batch_op:
        batch_op.alter_column('floor_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
